services:
  - type: web
    name: baomeng-linebot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: LINE_CHANNEL_SECRET
        value: 83e0cd34acc4b2e52ee311f0c0e8f0a2
      - key: LINE_ACCESS_TOKEN
        value: brcndl2dk1OmPOmUl3xm0L0xXVwLg8TeGbbRenHdnOTuiO1RKHxZxE7qs96wT2g2SVVotGgfDDVYTa7YvALkoz3Wy7cysmp/xllK7D+OZisjO0M6SpU9h+37ZQnzR+fnth+DJQxMTEM0wLytDdbvDAdB04t89/1O/w1cDnyilFU=
      - key: SUPABASE_URL
        value: https://swleodnzuojaavrzivcv.supabase.co
      - key: SUPABASE_KEY
        value: sb_publishable_FRN828NmQnE-bO2fP9KZ7A_i3A76-h-
